### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by wxnnvs** [is-really-cool/register#117]
If i go to is-really.cool it says the domain is for sale
Is this project still being worked on?

**Comment by purpleblueslime** [comment]
Yep...looks like this project is dead.

**Comment by wxnnvs** [comment]
> Yep...looks like this project is dead.

You've got some pretty sus things going on in your repo's lol 🧐

**Comment by Joabutt** [comment]
Check the discussions tab, updates there
