### ISSUE TITLE
Error 1014. CNAME Cross-User Banned

### ISSUE THREAD

**Issue by ghrlt** [is-really-cool/register#57]
Hi! First of all, thanks for your work and for merging #55 !

Anyway, the domain I provided is under Cloudflare free plan, meaning that I cannot request their support to allow Cross-User for my domain..
Is their anyway to, in your end, either use another record than CNAME or to disable Cloudflare? (i.e. doing like *.is-a.dev)

**Comment by Joabutt** [comment]
just send the cname you want me to put in here, ill check it and ill add it in

**Comment by ghrlt** [comment]
Hi. Re-opening this issue as it seems the problem isn't solved.. Was the CNAME record really successfully updated?

**Comment by Joabutt** [comment]
sorry, was really busy for the last couple of days. I updated the CNAME, do check and tell me if there are any more problems.

**Comment by ghrlt** [comment]
np. Thanks!

Even though it's finally working, might be worth telling that apparently adding `yoursubdomain.is-really.cool` to pages custom domain (repo -> settings -> pages -> custom domain) is mandatory.
![image](https://user-images.githubusercontent.com/75177329/233502197-73c218ab-e84e-454c-ba54-de98ebfad877.png)
Without doing this, the page was retuning a 404 error.
