### ISSUE TITLE
Vercel issue

### ISSUE THREAD

**Issue by elijah629** [is-really-cool/register#74]
I have successfully acquired a subdomain "elijah629.is-really.cool". But, when I try to add it it gives me this ugly error: ![image](https://user-images.githubusercontent.com/62805599/231056073-ed8703eb-e5bb-4336-8c8a-ba2bab892bc2.jpeg)

I don't know if you could do this, If you can't you can change my domain to a redirect.

**Comment by Elijah629** [comment]
I can send the full record if you can add it.

**Comment by Elijah629** [comment]
Bump.

**Comment by Elijah629** [comment]
Bump.

**Comment by Elijah629** [comment]
Bump.

**Comment by Satindar31** [comment]
Vercel is not supported by many providers like these. rip

**Comment by Joabutt** [comment]
Check the discussions tab, updates there
