### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by RaptaG** [is-really-cool/register#79]
My PR was merged three days ago (https://github.com/is-really-cool/register/pull/77, merged by @Joabutt) but the website still doesn't work.

Reproduce:
- Go to https://tom.is-really.cool
- See error: 
![error](https://user-images.githubusercontent.com/77157639/233783814-3340be5a-135f-410a-92cf-9fa29c65a62f.png)

**Comment by RaptaG** [comment]
Is it a server issue?

**Comment by RaptaG** [comment]
@Joabutt sorry for the ping spam but it's kinda hard to get your attention, are there any updates on this? I'm not the only one having this issue, for example #72 #73 #75 #76 have the same issue too..

**Comment by Joabutt** [comment]
sorry for inactivity, been going through some family issues for the past few weeks. I will need to get some helpers to help with the merging and management of the domains, please dm me on discord @ joabutt#0001 to apply, thanks.

**Comment by RaptaG** [comment]
This Discord username is invalid @Joabutt

**Comment by Joabutt** [comment]
its just joabutt now, after the recent discord change

**Comment by Joabutt** [comment]
Check the discussions tab, updates there
